"""Regenerate the checked-in icon subset; optional tooling, never needed by builds.

python3 -m venv /tmp/avalon-icons
/tmp/avalon-icons/bin/pip install fonttools==4.65.0 brotli==1.2.0 uharfbuzz==0.56.1
/tmp/avalon-icons/bin/python packages/ui/scripts/subset-material-icons.py
"""
from io import BytesIO
from pathlib import Path
import re
import json
import subprocess

from fontTools import subset
from fontTools.ttLib import TTFont
import uharfbuzz as hb

UI = Path(__file__).resolve().parents[1]
ROOT = UI.parents[1]
UPSTREAM = ROOT / 'node_modules/material-design-icons-iconfont/dist'
css = (UPSTREAM / 'material-design-icons.css').read_text()
codepoints = dict(re.findall(r'\.material-icons\.([\w]+):before\s*\{\s*content: "\\([0-9a-f]+)"', css))
# Shared coverage scanner excludes comments using the installed Vue/TS parsers.
names = json.loads(subprocess.check_output(['node', str(UI / 'scripts/material-icon-names.cjs')]))
font = TTFont(UPSTREAM / 'fonts/MaterialIcons-Regular.woff2', recalcTimestamp=False)
options = subset.Options()
# Keep only requested icon glyphs, not every ligature reachable from a-z.
options.layout_closure = False
subsetter = subset.Subsetter(options=options)
subsetter.populate(unicodes={int(codepoints[name], 16) for name in names}, text=''.join(names))
subsetter.subset(font)

# Shape every name and its codepoint with HarfBuzz: both must produce the same
# single, non-missing glyph. This catches lost GSUB ligatures and glyph coverage.
font.flavor = None
raw = BytesIO()
font.save(raw)
shaping_font = hb.Font(hb.Face(raw.getvalue()))
def shape(text):
    buffer = hb.Buffer()
    buffer.add_str(text)
    buffer.guess_segment_properties()
    hb.shape(shaping_font, buffer)
    return [info.codepoint for info in buffer.glyph_infos]
for name in names:
    literal = name.lstrip('_') if name.startswith('_') and name[1:2].isdigit() else name
    glyphs = shape(literal)
    assert len(glyphs) == 1 and glyphs[0] != 0, (name, glyphs)
    assert glyphs == shape(chr(int(codepoints[name], 16))), name

output = UI / 'src/assets/fonts'
output.mkdir(parents=True, exist_ok=True)
font.flavor = 'woff2'
font.save(output / 'material-icons.woff2')
(output / 'LICENSE.material-icons').write_text((UPSTREAM / 'LICENSE').read_text())
header = '''/* Generated by scripts/subset-material-icons.py; do not edit icon rules. */
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url('../assets/fonts/material-icons.woff2') format('woff2');
}

.material-icons {
  font-family: 'Material Icons';
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  display: inline-block;
  box-sizing: content-box;
  width: 1em;
  height: 1em;
  flex-shrink: 0;
  overflow: hidden;
  line-height: 1;
  text-transform: none;
  letter-spacing: normal;
  word-wrap: normal;
  white-space: nowrap;
  direction: inherit;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
  -moz-osx-font-smoothing: grayscale;
  font-feature-settings: 'liga';
}
'''
rules = '\n'.join(f'.material-icons.{name}::before {{ content: "\\{codepoints[name]}"; }}' for name in names)
(UI / 'src/styles/material-icons.css').write_text(header + '\n' + rules + '\n')
print(f'Verified {len(names)} icon ligatures and codepoints; subset: {(output / "material-icons.woff2").stat().st_size:,} bytes')
